sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - export FLASK_APP=run.py

# command to run tests
script:
  - "cd ${TRAVIS_BUILD_DIR} && py.test tests"
